name: Simple workflow
on: [push, pull_request]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the git repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build the code
        run: |
          npm run build
